name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install
      - run: npm run build

      - name: 🧹 Clean server (Safely)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            find /home/santapr/santa-prize.dp.ua/www -maxdepth 1 ! -name 'storage' ! -name '.env' ! -name 'www' ! -name '.' -exec rm -rf {} +

      - name: 📤 Upload files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "."
          target: "/home/santapr/santa-prize.dp.ua/www"

      - name: 🚀 Post-deployment commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/santapr/santa-prize.dp.ua/www
            php artisan storage:link
            
            # Fix permissions
            find storage -type d -exec chmod 755 {} +
            find storage -type f -exec chmod 644 {} +
            chmod -R 775 storage bootstrap/cache
            
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache